[build] Package build artifacts with `make jenkins` (#153)
Update the `make jenkins` target to package up the `bin` directory for
(hopeful) use on other machines.

The generated package is named:

	oss-xamarin-android_vVERSION_OS-ARCH_BRANCH_COMMIT.zip

where:

* **VERSION** is the new `$(ProductVersion)` MSBuild property
    along with the number of commits since `$(ProductVersion)`
    was *changed*
* **OS** is the name of the OS that built the package
* **ARCH** is the OS architecture
* **BRANCH** is the git branch being built (usually `master`)
* **COMMIT** is the git commit that was built.

For example:

	oss-xamarin.android_v7.0.99.0_Darwin-x86_64_jonp-zip-output_c4eab00.zip

The package file is *not* an installer, just a ZIP package, but should
contain everything needed to *create* an installer.

This also copies `tools/scripts/xabuild` into the appropriate
`bin/$(Configuration)/bin` directories so that an `xabuild` script is
installed as part of the package, and `xabuild` is updated to setup
the various environment variables accordingly so it is invokable from
the `bin/$(Configuration)/bin` directories.

diff --git a/tools/scripts/xabuild b/tools/scripts/xabuild
--- a/tools/scripts/xabuild
+++ b/tools/scripts/xabuild
@@ -1,26 +1,53 @@
 #!/bin/bash -e
-topdir="$(cd `dirname "$0"`/../.. && pwd)"
+
+name=$(basename "$0")
 
 if [ -z "$CONFIGURATION" ] ; then
 	CONFIGURATION=Debug
+fi
+
+xabuilddir="$(cd `dirname "$0"` && pwd)"
+
+if [[ "$xabuilddir" == */tools/scripts ]] ; then
+	topdir="$xabuilddir/../../bin/$CONFIGURATION"
+	Paths_targets="$xabuilddir/../../build-tools/scripts/Paths.targets"
+elif [[ "$xabuilddir" == */bin ]] ; then
+	topdir="$xabuilddir/.."
+else
+	(>&2 echo "$name: Could not determine location to Xamarin.Android locations.")
+	exit 1
 fi
 
 if [ -z "$MSBUILD" ] ; then
 	MSBUILD=xbuild
 fi
 
-export TARGETS_DIR="$topdir/bin/$CONFIGURATION/lib/xbuild"
-export MSBuildExtensionsPath="$TARGETS_DIR" 
-export MONO_ANDROID_PATH="$topdir/bin/$CONFIGURATION"
-export XBUILD_FRAMEWORK_FOLDERS_PATH="$topdir/bin/$CONFIGURATION/lib/xbuild-frameworks"
-ANDROID_NDK_PATH=$(xbuild /nologo /v:minimal /t:GetAndroidNdkFullPath $topdir/build-tools/scripts/Paths.targets)
-ANDROID_SDK_PATH=$(xbuild /nologo /v:minimal /t:GetAndroidSdkFullPath $topdir/build-tools/scripts/Paths.targets)
+if [ -z "$ANDROID_NDK_PATH" -a -f "$Paths_targets" ] ; then
+	ANDROID_NDK_PATH=$($MSBUILD /nologo /v:minimal /t:GetAndroidNdkFullPath "$Paths_targets")
+	ANDROID_NDK_PATH=$(echo $ANDROID_NDK_PATH | sed 's/^\w*//g')
+	export ANDROID_NDK_PATH
+fi
 
-ANDROID_NDK_PATH=$(echo $ANDROID_NDK_PATH | sed 's/^\w*//g')
-ANDROID_SDK_PATH=$(echo $ANDROID_SDK_PATH | sed 's/^\w*//g')
+if [ -z "$ANDROID_SDK_PATH" -a -f "$Paths_targets" ] ; then
+	ANDROID_SDK_PATH=$($MSBUILD /nologo /v:minimal /t:GetAndroidSdkFullPath "$Paths_targets")
+	ANDROID_SDK_PATH=$(echo $ANDROID_SDK_PATH | sed 's/^\w*//g')
+	export ANDROID_SDK_PATH
+fi
 
-export ANDROID_NDK_PATH
-export ANDROID_SDK_PATH
+if [ -z "$ANDROID_NDK_PATH" ] ; then
+	>&2 echo "$name: Could not determine Android NDK path. Please export the \$ANDROID_NDK_PATH environment variable."
+	exit 1
+fi
+
+if [ -z "$ANDROID_SDK_PATH" ] ; then
+	>&2 echo "$name: Could not determine Android SDK path. Please export the \$ANDROID_SDK_PATH environment variable."
+	exit 1
+fi
+
+export TARGETS_DIR="$topdir/lib/xbuild"
+export MSBuildExtensionsPath="$TARGETS_DIR"
+export MONO_ANDROID_PATH="$topdir"
+export XBUILD_FRAMEWORK_FOLDERS_PATH="$topdir/lib/xbuild-frameworks"
 
 exec $MSBUILD /p:Configuration=$CONFIGURATION $MSBUILD_OPTIONS \
 	/p:AndroidNdkDirectory="$ANDROID_NDK_PATH" \
